platform :ios, '10.0'
use_frameworks!

target 'rest-it' do
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: 'true'
end
